### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by ricewang666** [symbol/symbol-docs#930]
hi can you help me

**Comment by ricewang666** [comment]
verbose: error raised by node:7900 connection:  certificate has expired {"code":"CERT_HAS_EXPIRED","stack":"Error: certificate has expired\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket._finishInit (node:_tls_wrap:953:8)\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12)","timestamp":"2023-01-10T10:40:49.500Z"}
error: caught error 503 connection failed {"body":{"code":"ServiceUnavailable","message":"connection failed"},"jse_info":{},"jse_shortmsg":"connection failed","stack":"ServiceUnavailableError: connection failed\n    at Object.createServiceUnavailableError (/app/src/server/errors.js:56:44)\n    at TLSSocket.<anonymous> (/app/src/connection/connectionService.js:104:20)\n    at TLSSocket.emit (node:events:525:35)\n    at node:net:301:12\n    at TCP.done (node:_tls_wrap:588:7)","timestamp":"2023-01-10T10:40:49.500Z"}

**Comment by ricewang666** [comment]
and now the blocks are out of sync，can you help me out ?
image: symbolplatform/symbol-server:gcc-1.0.3.5

**Comment by Wayonb** [comment]
Hi, Here is the docs on cert renewal - https://github.com/fboucquez/symbol-bootstrap/blob/dev/docs/renewCertificates.md

If you need further help you should ask on discord - https://discord.com/channels/856325968096133191/862674505193488415

**Comment by ricewang666** [comment]
@Wayonb it works, thank you for your help !
